# Generated by Django 5.0.3 on 2024-03-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_user_last_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mailexpense',
            table='mailexpense',
        ),
    ]
