# Generated by Django 5.0.3 on 2024-03-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_mailexpense_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user_id',
        ),
    ]
