# Generated by Django 5.0.3 on 2024-03-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_userstatus_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user'),
        ),
    ]
